version: '2'

services:
  java-restapp:
    image: maven:3-jdk-8
    volumes:
      - $PWD/java-restapp:/usr/src/java-restapp:ro
    ports:
      - "8081:8080"
    command: "bash -c 'cp -r /usr/src/java-restapp /tmp/java-restapp; cd /tmp/java-restapp; mvn clean package exec:java'"

  promserver:
    image: prom/prometheus:0.19.2
    volumes:
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - $PWD/prometheus/console/consoles:/etc/prometheus/consoles:ro
      - $PWD/prometheus/console/console_libraries:/etc/prometheus/console_libraries:ro
  #    - $PWD/alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    extra_hosts:
      - node-exporter-host:$DOCKER_HOST_IP
    links:
      - node-exporter-container1
      - node-exporter-container2
      - cadvisor
      - consul-server

  registrator:
    image: gliderlabs/registrator:v7
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-internal consul://consul-server:8500"
    depends_on:
      - consul-server
      - cadvisor
    links:
      - consul-server

  consul-server:
    image: gliderlabs/consul-server:0.6
    ports:
      - 8500:8500
    command: "-bootstrap"

  grafana:
    image: grafana/grafana:3.0.4
    ports:
      - 3000:3000

  cadvisor:
    image: google/cadvisor:v0.23.2
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "8080:8080"

  node-exporter-container1:
    image: prom/node-exporter:0.12.0
  node-exporter-container2:
    image: prom/node-exporter:0.12.0

  node-exporter-host:
    image: prom/node-exporter:0.12.0
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    ports:
      - "9100"
    network_mode: host
    command: "-collector.procfs /host/proc -collector.sysfs /host/proc -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($$|/)'"
